### ISSUE TITLE
Crashes on specific file in neovim

### ISSUE THREAD

**Issue by moniquelive** [MDeiml/tree-sitter-markdown#111]
**Describe the bug**
When I launch nvim opening [this file](https://github.com/moniquelive/meuastral/blob/main/README.md) it simply closes with no messages whatsoever.

Sorry but I don't know how to repro it using tree-sitter-markdown standalone.

**Expected behavior**
Neovim opens the file

**Actual behavior**
Neovim closes prematurely

**Comment by clason** [comment]
Cannot reproduce (with Neovim HEAD, which bundles this parser).

**Comment by moniquelive** [comment]
I managed to run from a linux box with the same setup and the debugging tools are way better.
I ran `gdb nvim` and then `run README.md`.

On Mac:

```shell
🍎 ❯ nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

On PC:
```shell
🍭 ❯ nvim --version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az178-366
```

Looking at frame #3 it seems like the ELM parser picked it up?! Here's the Linux stack trace:

```gdb
(gdb) bt
#0  0x0000555555951d24 in ts_decode_utf8 ()
#1  0x0000555555951f27 in ts_lexer.get_lookahead ()
#2  0x00005555559522b2 in ts_lexer.get_column ()
#3  0x00007ffff57302bb in tree_sitter_elm_external_scanner_scan () from /home/cyber/.local/share/nvim/lazy/nvim-treesitter/parser/elm.so
#4  0x000055555593f03a in ts_parser_parse ()
#5  0x000055555574f67e in parser_parse.lto_priv ()
#6  0x00005555559773f6 in lj_BC_FUNCC ()
#7  0x00005555559637f6 in lua_pcall (L=0x7ffff7e65380, nargs=<optimized out>, nresults=1, errfunc=<optimized out>) at lj_api.c:1116
#8  0x000055555573ed08 in nlua_pcall ()
#9  0x0000555555744640 in nlua_call_ref ()
#10 0x0000555555631937 in getnextac ()
#11 0x00005555556daecc in do_cmdline ()
#12 0x0000555555630b38 in apply_autocmds_group ()
#13 0x00005555557c8cc0 in did_set_string_option ()
#14 0x00005555557cb61f in set_string_option ()
#15 0x00005555556e3e73 in ex_setfiletype.lto_priv ()
#16 0x00005555556d7d8d in execute_cmd0 ()
#17 0x00005555556d83e4 in execute_cmd ()
#18 0x0000555555604e0b in nvim_cmd ()
#19 0x00005555555e8fba in nlua_api_nvim_cmd.lto_priv ()
#20 0x00005555559773f6 in lj_BC_FUNCC ()
#21 0x00005555559637f6 in lua_pcall (L=0x7ffff7e65380, nargs=<optimized out>, nresults=1, errfunc=<optimized out>) at lj_api.c:1116
#22 0x000055555573ed08 in nlua_pcall ()
#23 0x0000555555744640 in nlua_call_ref ()
#24 0x00005555555ffe7f in nvim_buf_call ()
#25 0x00005555555e886b in nlua_api_nvim_buf_call.lto_priv ()
#26 0x00005555559773f6 in lj_BC_FUNCC ()
#27 0x00005555559637f6 in lua_pcall (L=0x7ffff7e65380, nargs=<optimized out>, nresults=1, errfunc=<optimized out>) at lj_api.c:1116
#28 0x000055555573ed08 in nlua_pcall ()
#29 0x0000555555744640 in nlua_call_ref ()
#30 0x0000555555631937 in getnextac ()
#31 0x00005555556daecc in do_cmdline ()
#32 0x0000555555630b38 in apply_autocmds_group ()
#33 0x00005555556faad6 in readfile ()
#34 0x00005555556383fb in open_buffer ()
#35 0x00005555555e26fd in main ()
```

**Comment by moniquelive** [comment]
Bingo https://github.com/elm-tooling/tree-sitter-elm/issues/124
Sorry for the noise!
